### ISSUE TITLE
CSS使用伪元素提示消息文字

### ISSUE THREAD

**Issue by facebook201** [facebook201/CSS-secret#10]
```HTML
    <span class="haorooms" data-content="前">前</span>
    <span class="haorooms" data-content="端">端</span>
    <span class="haorooms" data-content="博">博</span>
    <span class="haorooms" data-content="客">客</span>
```

```CSS
    .haorooms {
    position:relative;
    display:inline-block;
    font-size:80px; /*  任何宽度都可以 */
    color: black; /* 任何颜色，或透明 */
    overflow:hidden;
    white-space: pre; /* 处理空格 */
}
.haorooms:before {
    display:block;
    z-index:1;
    position:absolute;
    top:0;
    left:0;
    width: 50%;
    content: attr(data-content); /* 伪元素的动态获取内容 */
    overflow:hidden;
    color: #f00;
}
```
