### ISSUE TITLE
CSS文字怎么两端对齐 例如表单填写信息前面的说明文字

### ISSUE THREAD

**Issue by facebook201** [facebook201/CSS-secret#11]
```HTML
<div class="justify">hello, text justify.</div><br/>
<div class="justify"> hello, text justify.<span></span></div><br/>
<div class="justify">中 文 两 端 对 齐</div><br/>
<div class="justify">中 文 两 端 对 齐<span></span></div>
```

```CSS
div.justify { text-align: justify; width:200px; font-size:15px; color:red; border:1px solid blue; height:18px;}
div.justify > span { display: inline-block /* Opera */; padding-left: 100%; }
```
关键在于 块级化 以及 text-align: justify; 然后还有就是后面加一个空的元素span padding-left： 100%；
