### ISSUE TITLE
表单布局 以及文字两端对齐

### ISSUE THREAD

**Issue by facebook201** [facebook201/CSS-secret#12]
```HTML
	<div class="form">
			<div class="filed type-filed">
				<label for="CHAN_type" class="label-text">选择车型 <span></span></label>
				<input type="text" name="CHAN_type" id="CHAN_type" class="login-text" tabindex="1" /> 
			</div>
			<div class="filed agency-filed">
				<label for="CHAN_agency" class="label-text">选择经销商 <span></span></label>
				<input type="text" name="CHAN_agency" id="CHAN_agency" class="login-text" tabindex="2">
			</div>
			<div class="filed username-filed">
				<label for="CHAN_username" class="label-text">姓名 <span></span></label>
				<input type="text" name="CHAN_username" id="CHAN_username" class="login-text"  tabindex="3">
			</div>
			<div class="filed phonenumber-filed">
				<label for="CHAN_phonenumber" class="label-text">手机 <span></span></label>
				<input type="text" name="CHAN_phonenumber" id="CHAN_phonenumber" class="login-text" tabindex="4">
			</div>
			<div class="filed message-filed" >
				<label for="" class="label-text">短信验证 <span></span></label>
				<input type="text" name="CHAN_message" id="CHAN_message" class="login-text" tabindex="5">
			</div>
			<div class="filed submit-filed">
				<a href="javascript:;">提交</a>
			</div>
		</div>
```

```CSS
.form{
        margin-top: 50px;
        padding: 0 62px;
        color: #737272;
        .filed{
            position: relative;
            margin-top: 40px;
            margin-bottom: 40px;
            height: 60px;
            .label-text{
                position: absolute;
                top: 0;
                left: 0;
                display: block;
                line-height: 60px;
                height: 60px;
                width: 150px;
                text-align: justify;
                font-size: 26px;
                &>span{
                    padding-left: 100%;
                }
            }
        }
        .login-text{
            position: absolute;
            top: 0;
            right: 0;
            height: 60px;
            line-height: 60px;
            width: 440px;
            font-size: 14px;
            border: 1px solid #b5b5b5;
            border-radius: 10px;
        }
```
