### ISSUE TITLE
CSS 处理下拉框

### ISSUE THREAD

**Issue by facebook201** [facebook201/CSS-secret#13]
## 有的时候我们为了设计好看。去掉默认的下拉框样式。
```CSS
select{outline: none;  appearance:none;   // 这里会去掉默认的下拉。
  -moz-appearance:none;
  -webkit-appearance:none;}

.select{
    background: transparent; // 透明 然后配上图片 和 z-index 就可以实现了 如果位置不理想 可定位一下
}
```
