### ISSUE TITLE
Margin系列之margin

### ISSUE THREAD

**Issue by facebook201** [facebook201/CSS-secret#3]
## margin
什么是margin？ 规范里面说了
原文：Margins in CSS serve to add both horizontal and vertical space between boxes.
翻译：CSS中的margin用来添加盒子之间的水平和垂直间隙。

top, right, bottom, left:

原文：An element is said to be positioned if its ‘position’ property has a value other than ‘static’. Positioned elements generate positioned boxes, and may be laid out according to the following four physical properties: top, right, bottom, left.

翻译：一个元素的position属性值如果不为static则发生定位。定位元素会产生定位盒，并且会根据 top, right, bottom, left 这4个物理属性进行排版布局。
意思很明白，margin 是用来增加自身与它人之间的空白，而 top, right, bottom, left 是用来对自身进行排版，作用完全不同。也就是说 margin 是互动的，因为它要影响它人；而 top, right, bottom, left是孤独的，它只是自己一个人玩，不影响它人。

### 假设一下 如果我们使用 margin-bottom： 50px； 和 bottom： 50。会有什么不一样
```HTML
<div class='margin'>
    <p class="margin-bottom">ssss</p>
    <p class="bottom">sss</p>
</div>
```
```CSS
p{display: inline-block;padding: 10px;}
.margin>margin-bottom{
    margin-bottom: 50px;
}
.margin>bottom{
    margin: 50px;
}
```
margin 是用来增加自身与它人之间的间隙，所以它距包含块底部有50px，这应该能理解？那为什么 bottom会跑到上面去？相信仔细看了之前的描述，你应该知道。因为它要相对自己的底部边缘有50px，恩，不是-50px，所以它等于是向上偏移了50px。还有一个细节你注意到了吗？bottom 没有撑开它的包含块，仔细看看它的包含块的背景色区域。这正好也验证了之前说的 top, right, bottom, left 是孤独的，它只是自己一个人玩，不影响它人。
