### ISSUE TITLE
能使用CSS解决的问题就不要使用js

### ISSUE THREAD

**Issue by facebook201** [facebook201/CSS-secret#5]
## 导航高亮
导航菜单 里面高亮 使用hover高亮。你可以使用js控制 但是用一点点 css技巧也是可以达到这个目的。
```CSS
ul li{
        display: inline-block;
        flex: 1;
        color: white;
	font-size: 20px; /* inline-block 去空白符 */
	background-color: pink;
	opacity: .5;
        filter: alpha(opacity=50);
}
ul li:hover{
        opacity: 1;
        filter: alpha(opacity=100);
}
```
## 自定义 checkbox样式
```CSS
input[type=checkbox]:checked + .checkbox{
}
```
### CSS3 伪类 改变图标字体颜色
```CSS
/* 正常状态为浅色 */
icon-search{
    color: #ccc;
}
input[type=search]:focus + .icon-search{
    color: #111;
}
```
