### ISSUE TITLE
CSS实用技巧代码

### ISSUE THREAD

**Issue by facebook201** [facebook201/CSS-secret#6]
### 基于文件格式实用不同的样式
a 超链接查看文件的时候
```CSS
/* http */
a[href="http://"]{
    padding-right: 20px;
    background: url(external.gif) no-repeat center right;
}
/* emails */
a[href="mailto:"]{
    padding-right: 20px;
    background: url(external.gif) no-repeat center right;
}
/* pdf */
a[href$=".pdf"]{
    padding-right: 20px;
    background: url(external.gif) no-repeat center right;
}
```
### 背景渐变动画
```CSS
button{
	background-image: linear-gradient(#5187c4, #1c2f45);
	background-size: auto 20%;
	background-position: 0 100%;
	transition: background-position 0.5s;
}
button:hover{
	background-position: 0 0;
}
```
### 包裹长文本
当碰到一个比自身还要长的文本 。
pre{
    white-space: pre-line;
    word-wrap: break-word;
}

### 省略号动画
.loading:after{
    overflow: hidden;
    display: inline-block;
    vertical-align: bottom;
    animation: ellipsis 2s infinite;
    content: '\2026';
    color: #f00;  // 颜色字体自拟
    font-size: 20px;
}
