### ISSUE TITLE
CSS常见问题的解决方案之chrome input autofill

### ISSUE THREAD

**Issue by facebook201** [facebook201/CSS-secret#7]
### chrome input autofill 
chrome浏览器器的背景图框会有自动填充的颜色 所以我们要兼容低版本的浏览器。

### 解决方案一 box-shadow
```CSS
input:-webkit-autofill {
    -webkit-box-shadow: 0 0 0px 1000px white inset;
}
```
### 解决方案二 animation
```CSS
@-webkit-keyframes setbackgroundcolor{
    to {
            background: transparent;     
    }
}
input:-webkit-autofill {
    -webkit-animation-name: setbackgroundcolor;
   -webkit-animation-fill-mode: forwards;
}
```
