### ISSUE TITLE
CSS之margin Position: relative  absolute fixed 之间的关系

### ISSUE THREAD

**Issue by facebook201** [facebook201/CSS-secret#9]
### 1 margin百分比值
我们知道 margin如果设置为百分比值。那么它会根据父元素的宽度来取值。但是绝对定位下面的 margin百分比是怎么取值呢？首先我们就要先来深刻的认知一下 这几个定位属性。

### 2 position：定位属性
    在脱离文档流(absolute,fixed)的定位元素中(如:小黑块),则margin百分比值是最近一个有定位设置(relative,absolute,fixed)的父级对象进行绝对定位父元素的width 计算的,若对象父级没有设置定位属性(absolute,fixed,relative),则 margin 百分比值是依据 body的 width 计算的。

  * position:fixed: 固定的参照对像是可视窗口而并非是body或是父级元素。可通过z-index进行层次分级
  * position:absolute: 脱离文档流，通过 top,bottom,left,right 定位。选取其最近一个有定位设置(relative,absolute,fixed)的父级对象进行绝对定位，如果对象的父级没有设置定位属性，absolute元素将以body坐标原点进行定位，可以通过z-index进行层次分级。
  * relative(相对定位): 对象不可层叠、不脱离文档流，参考自身静态位置通过 top,bottom,left,right 定位，并且可以通过z-index进行层次分级。

### 3 margin重叠(Collapsing margins)
  * Collapsing margins 的初衷就是为了让段落显示的更加好看。以由几个段落组成的典型文本页面为例。第一个段落上面的空间等于段落的上外边距。如果没有外边距合并，后续所有段落之间的外边距都将是相邻上外边距和下外边距的和。这意味着段落之间的空间是页面顶部的两倍。如果发生外边距合并，段落之间的上外边距和下外边距就合并在一起，这样各处的距离就一致了。
  * Collapsing margins 类型
 CSS 里面关于折叠的条件：
       两个块元素要产生折叠现象，必须满足一个必备条件：这两个元素的 margin 必须是相邻的；那么如果定义相邻呢，w3c 规范，两个 margin 是邻接的必须满足以下条件：
 ### A) 必须是处于常规文档流（非float和绝对定位）的块级盒子,并且处于同一个 BFC 当中
 ### B)  没有inline盒子，没有空隙，没有 padding 和 border 将他们分隔开
 ### C) 都属于垂直方向上相邻的外边距

margin 重叠的最直接的解决方法：让元素处于不同的BFC属性下。

### 4 兄弟元素的margin 重叠
   * 发生在同一父级块级元素下面
   * 父子元素的 margin 重叠
```CSS
//style
.first-block {
    background: #F44336;
    width: 200px;
    height: 200px;
}
.second-block {
    background: #00BCD4;
    width: 200px;
    height: 200px;
}
//html
<div class="first-block"></div>
<div class="second-block">
    <h2>我是有默认 margin 的 H2元素</h2>
</div>
```
为什么 first-block 和 second-block 之间会有这么宽的间距？
原因是：外边距折叠，这个间距是 h2 的上外边距引起的。
解决方案： 边框 外边距  overflow: hidden; 形成一个新的 BFC 

### Collapsing margins 解决方法
       float、inline-block 元素、绝对定位元素的 margin 不会和垂直方向上其他元素的 margin 折叠 ( 针对 兄弟元素)
　   注意: float , inline-block元素 , 绝对定位元素 都属于 BFC元素。
　　*：创建了块级格式化上下文(BFC, blocking formatting context )的父元素，比如说overflow:hidden，不和它的子元素发生 margin 折叠 (针对 父子元素)。
　　*：给父元素添加以下内容之一都可以避免发生 margin 重叠 。如 添加 border或者使用 padding来代替 margin。(针对 父子元素)
 
```CSS
 .container{
            background-color: pink;
            width:300px;
            height:300px;
            margin:10px;
            /*处理margin 重叠的方法*/
            /*overflow: hidden | scroll | auto;*/
            /*display: inline-block |flex | table | inline-block | inline-flex | inline-table | list-item | table-caption | table-cell*!*/
            /*float: left | right;*/
            /*position:absolute |fixed;*/
            display: inline-block;
        }
        .content{
            background-color: #000000;
            width:100px;
            height:100px;
            margin:10%;
        }
```
